"""Add student-facing oral notes to the official ClosetAI exam deck."""

from __future__ import annotations

import argparse
from pathlib import Path

from pptx import Presentation


NOTES = [
    """Apro con la tesi, non con gli algoritmi. ClosetAI nasce da una domanda quotidiana: prima di comprare un altro capo, possiamo usare meglio ciò che abbiamo già? La presentazione è divisa in due parti. Nella prima seguiremo Marta, una persona narrativa, lungo tutto il percorso dell’app: inserimento, uso, outfit, ghost garments, stato, gap e seconda vita. Nella seconda distingueremo con precisione quattro cose diverse: modello pre-addestrato, modelli allenati da noi, regole trasparenti e AI generativa. Dichiariamo fin dall’inizio che l’AI generativa è stata usata anche per sviluppare il progetto, preparare i materiali e creare il concept del logo, sempre con controllo umano. La tesi finale sarà: usare l’AI dove riduce davvero l’incertezza e mantenere spiegabile tutto il resto.""",
    """Immaginiamo Marta davanti all’armadio: possiede molti capi, ma finisce per scegliere quasi sempre gli stessi. La giacca verde rimane invisibile. Marta non deriva da uno studio utenti: è una user story che ci aiuta a descrivere il problema. Il contesto ambientale, invece, è documentato. L’European Environment Agency riporta per il 2022 circa 19 chilogrammi di tessili consumati e circa 16 chilogrammi di rifiuti tessili per persona nell’Unione Europea. Non usiamo questi numeri per promettere che l’app risolverà il problema del settore; servono a mostrare perché allungare la vita utile e ridurre acquisti non necessari è una direzione rilevante. La domanda di progetto è quindi: come possiamo restituire a Marta memoria e contesto sulle sue scelte?""",
    """Il percorso comincia con una foto. Marta carica l’immagine del capo e crea una scheda con nome, categoria, colore, prezzo e data di acquisto, quando disponibili. Il punto importante da comunicare è che la scheda non diventa una verità incontestabile prodotta dall’AI: i campi restano visibili e correggibili. Questa scelta tutela sia l’usabilità sia la qualità dei dati. Dal punto di vista funzionale la foto collega un gesto semplice a un record strutturato, che potrà poi essere associato agli utilizzi, allo stato, alle raccomandazioni e alle azioni circolari. Durante la demo mostrerei prima il caricamento, poi la scheda, e direi esplicitamente che descrizione del capo e diagnosi dello stato sono due processi distinti.""",
    """Quando Marta indossa un capo, registra un utilizzo. Nel tempo, questi eventi rendono visibile la rotazione reale del guardaroba. Da prezzo e numero di utilizzi calcoliamo il cost-per-wear: prezzo diviso utilizzi. L’esempio mostra che un capo da 100 euro passa da 100 euro per uso, dopo il primo utilizzo, a 10 euro per uso dopo dieci utilizzi. È una formula semplice e trasparente, non un modello di machine learning. Va presentata con una cautela: non misura il valore affettivo, la qualità o la sostenibilità totale del capo e dipende dalla completezza del registro. Il suo valore è decisionale: aiuta Marta a distinguere ciò che usa davvero da ciò che occupa spazio senza entrare nella sua routine.""",
    """La schermata Oggi crea un outfit con capi già presenti. Il ranking è una regola pesata, non una rete neurale addestrata. Considera soprattutto compatibilità dei colori e meteo, può aggiungere un bonus a un ghost garment eleggibile e applica un piccolo aggiustamento dal feedback. Nella spiegazione orale conviene sottolineare due vantaggi: la proposta è comprensibile e può riportare in rotazione la giacca verde senza imporla. Non diciamo che l’AI “capisce lo stile” di Marta: oggi la combinazione deriva da pesi dichiarati. Il feedback rende il sistema adattabile, ma i suoi limiti restano visibili. Questa è una scelta importante del progetto: non usare un modello complesso quando una regola auditabile soddisfa meglio il bisogno.""",
    """Qui rispondo in modo diretto alla domanda sui ghost garments: sì, vengono rilevati. La regola richiede tre condizioni contemporanee: il capo è attivo, ha zero utilizzi registrati ed è posseduto da almeno la soglia scelta, 30 giorni per default. Se manca la data di acquisto, usiamo la data di inserimento. Quindi ghost significa “mai indossato dopo almeno 30 giorni”, non semplicemente “usato poco”: dopo un solo utilizzo non è più ghost secondo questa definizione. Nell’interfaccia il risultato è visibile in tre punti: nella dashboard come metrica e lista dei capi da riscoprire; nel dettaglio come badge con soglia esplicita; nella proposta di outfit come segnale anti-fantasma. Preciso anche che questa è logica deterministica, non machine learning.""",
    """Quando Marta ritrova la giacca, vuole sapere in che stato si trova. Le tre classi sono buono, usurato e danneggiato. Con una foto e il checkpoint disponibili, Fashion-CLIP pre-addestrato produce l’embedding visivo e la nostra piccola MLP propone una classe. Se il modello o l’immagine non sono disponibili, l’app può usare un fallback euristico basato sui dati disponibili. In ogni caso il risultato indica la sua origine e Marta può confermare o correggere lo stato. Questo punto è importante durante l’esame: non presentiamo il modello come certificazione professionale né come diagnosi certa. Riduce l’incertezza e collega l’esito a una decisione di cura: continuare a usare, riparare o scegliere una seconda vita.""",
    """La gap analysis osserva il guardaroba nel suo insieme. Gli input sono 14 segnali aggregati: quantità per ruolo, stagionalità, varietà cromatica, presenza di neutri, rapporto dei ghost e totale dei capi. L’output contiene sei possibili gap e può essere multi-label, quindi più risposte possono essere vere insieme. Il messaggio di prodotto più importante è che un gap non equivale automaticamente a un acquisto: il sistema può concludere che non serve comprare nulla oppure segnalare una sovrabbondanza. Le probabilità sono tradotte in consigli che privilegiano riuso, combinazioni e seconda mano. Il limite va dichiarato: il modello è stato addestrato su guardaroba simulati con label derivate da regole esperte, quindi prima di un uso reale servono dati e validazione esterna.""",
    """Il ciclo si chiude con un’azione: continuare a usare il capo, ripararlo, donarlo, venderlo o avviarlo alla corretta seconda vita. L’impatto verde mostrato dall’app è calcolato come media indicativa della categoria moltiplicata per un fattore dell’azione. Lo definiamo sempre stima di scenario in chilogrammi di CO2 equivalente. Non è una misura fisica, non è una Life Cycle Assessment completa e dipende dall’ipotesi che l’azione eviti almeno in parte un nuovo acquisto. Questa trasparenza è essenziale nell’esame: il numero serve a confrontare ordini di grandezza e rendere visibile una conseguenza, non a certificare un beneficio assoluto. Come sviluppo futuro proponiamo dati per materiale, fonti LCA più granulari e intervalli d’incertezza.""",
    """Rileggiamo ora la storia come una sequenza verificabile: Marta fotografa, usa, riscopre, cura e decide. Nel dataset dimostrativo abbiamo 12 capi attivi, 2 ghost garments, 2 azioni circolari e 57,5 chilogrammi di CO2 equivalente come stima di scenario. Ho volutamente evitato di fissare in slide il numero degli utilizzi, perché cambia mentre eseguiamo la demo. È importante non confondere questi valori con risultati scientifici: rendono la dimostrazione coerente e ripetibile, ma non sono uno studio utenti e non dimostrano un impatto ambientale reale. A questo punto abbiamo mostrato il prodotto senza sovraccaricarlo di termini tecnici; ora possiamo entrare nelle scelte di AI e spiegare da dove proviene ogni output.""",
    """Questa è una slide di passaggio alla demo web. La dimostrazione dovrebbe durare tra tre e quattro minuti e seguire un solo capo, senza visitare ogni schermata. L’ordine suggerito è: aprire il capo nel catalogo; registrare un utilizzo; mostrare la metrica o lista ghost; eseguire o mostrare lo stato e la gap analysis; registrare un’azione circolare e leggere l’impatto come stima. Per ogni passaggio uso la stessa frase guida: qual è l’input, quale trasformazione avviene, quale output vedo, quale beneficio offre e quale limite devo dichiarare. Se una funzione non è disponibile durante la demo, non improvviso: mostro il dato già preparato o passo alla slide successiva, spiegando il comportamento atteso.""",
    """Ora separiamo quattro categorie che spesso vengono chiamate tutte genericamente AI. Fashion-CLIP è pre-addestrato da altri e noi lo usiamo congelato. Le due MLP per stato e gap sono addestrate da noi. Ghost, outfit, cost-per-wear e impatto sono regole o formule trasparenti. Infine l’AI generativa è stata usata nel processo di creazione: ideazione, architettura, supporto al codice, test, documentazione, presentazione e concept del logo. Gli output generativi non sono stati accettati automaticamente: sono stati confrontati con repository, test e dati. Nel runtime, testi LLM e virtual try-on restano opzionali e non sono modelli addestrati da noi. Questa distinzione ci consente di rispondere con precisione alla domanda: “che cosa avete davvero allenato?”""",
    """I modelli allenati da noi sono due. Per lo stato, Fashion-CLIP congelato trasforma la foto in 512 valori; la nostra MLP 512-256-128-3 produce buono, usurato o danneggiato. Sul holdout locale di circa 600 immagini otteniamo circa il 94 per cento di accuracy, senza validazione esterna. Per i gap, una seconda MLP riceve 14 segnali e produce sei probabilità; su 5.000 guardaroba simulati raggiunge una micro-F1 di circa 0,943. Le label derivano da regole, quindi il dato non prova generalizzazione su utenti reali. Abbiamo preparato cinque notebook autonomi e commentati: due riproducono i modelli runtime; tre documentano esperimenti accademici su rischio ghost, previsione degli utilizzi e clustering e non sono collegati alla UI.""",
    """Questa slide documenta il workflow generativo richiesto dalla traccia. Un prompt valido include contesto, obiettivo, vincoli, formato di uscita e controlli. L’output diventa una bozza; confrontiamo alternative e trade-off; verifichiamo con repository, test e metriche; infine correggiamo. Tre esempi di allucinazioni bloccate sono: quattro stati inventati invece delle tre classi reali; un VLM dichiarato nella UI ma assente dal runtime; la CO2 presentata come dato certo invece che stima di scenario. Il logo segue lo stesso metodo: concept creato con AI generativa, poi implementato e verificato come SVG editabile nel repository. Il file docs/prompt-register-progetto.md raccoglie tool, prompt riproducibili, tentativi e correzioni; è un registro consolidato, non un log automatico verbatim delle chat storiche.""",
    """Durante la demo ML non mi limito a mostrare la percentuale. Per il modello stato mostro una foto, spiego che Fashion-CLIP è congelato, carico il checkpoint della nostra MLP e leggo la classe proposta; poi ricordo il limite del holdout locale. Per il modello gap mostro i 14 segnali aggregati, le sei probabilità e il consiglio finale; poi ricordo che training e label sono simulati. Se apro un notebook, scelgo uno dei due runtime: eseguo le celle principali, faccio vedere caricamento dati, definizione del modello, training, metriche e salvataggio del checkpoint. I notebook sono auto-contenuti e commentati per permettere al professore di seguire il ragionamento anche senza conoscere in dettaglio PyTorch.""",
    """L’architettura separa client React, API FastAPI, dati e modelli. Questo rende il prototipo comprensibile e consente di sostituire componenti senza riscrivere tutto. La fattibilità va discussa in tre dimensioni. Costi: lo stack è prevalentemente open source; pesano tempo di sviluppo e servizi cloud generativi opzionali. Materiali: bastano smartphone e laptop esistenti, senza hardware dedicato nel prototipo. Scalabilità: SQLite può diventare PostgreSQL, i file locali object storage, e si possono aggiungere autenticazione, job asincroni e monitoraggio. Per lo smartphone il primo passo razionale è una PWA installabile; wrapper o app nativa hanno senso solo se camera, push e offline diventano requisiti centrali. Prima della produzione servono sicurezza, isolamento utenti e verifica GDPR.""",
    """Chiudo con un bilancio. Il beneficio potenziale nasce da maggiore rotazione, cura prima della sostituzione, minori acquisti non necessari e seconda vita documentata. Esiste però un costo digitale: training, inferenza, storage delle immagini, servizi generativi esterni, dispositivi e rete. Le mitigazioni già presenti o progettate sono backbone congelato, reti piccole, inferenza locale, caching e generazione opzionale. Non dichiariamo un impatto netto positivo senza dati reali: servono sperimentazione con utenti, misure del comportamento, fonti LCA e intervalli d’incertezza. La checklist finale mostra che la consegna copre problem setting, workflow e prompt, confronti e allucinazioni, ML con notebook Python, fattibilità e sostenibilità. La frase conclusiva riassume la nostra scelta: usare l’AI dove riduce davvero l’incertezza e mantenere spiegabile tutto il resto.""",
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    deck = Presentation(args.input)
    if len(deck.slides) != len(NOTES):
        raise ValueError(f"Expected {len(NOTES)} slides, found {len(deck.slides)}")

    for slide, note in zip(deck.slides, NOTES, strict=True):
        frame = slide.notes_slide.notes_text_frame
        frame.clear()
        frame.text = note

    deck.core_properties.title = "ClosetAI — Presentazione ufficiale d'esame"
    deck.core_properties.subject = "User story, AI generativa, machine learning, fattibilità e sostenibilità"
    deck.core_properties.comments = "Include 17 note orali in italiano, una per ogni slide, destinate allo studente che espone."
    args.output.parent.mkdir(parents=True, exist_ok=True)
    deck.save(args.output)
    print(f"Saved {args.output} with {len(NOTES)} speaker notes")


if __name__ == "__main__":
    main()
