"""Add the official oral commentary to the generated ClosetAI deck.

The visual deck is built with artifact-tool.  This small post-processing step
uses python-pptx only to populate PowerPoint's native speaker-notes parts.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from pptx import Presentation


NOTES = [
    """Oggi non vorrei partire dagli algoritmi, ma da una decisione quotidiana: prima di comprare un altro capo, possiamo usare meglio ciò che possediamo? ClosetAI nasce per rispondere a questa domanda. Ve lo raccontiamo seguendo Marta, una persona immaginaria ma rappresentativa, dal primo inserimento di un capo fino alla cura o alla seconda vita. In questo percorso vedremo quattro segnali concreti: utilizzo, capi fantasma, stato di conservazione e gap del guardaroba. Solo nella seconda parte apriremo la scatola tecnica e distingueremo con precisione ciò che abbiamo addestrato noi, ciò che è pre-addestrato, ciò che è una regola e ciò che è generativo. La nostra tesi è semplice: l’AI ha valore quando riduce un’incertezza utile; il resto deve rimanere trasparente.""",
    """Per capire il bisogno, immaginiamo Marta davanti all’armadio. Ha molti capi, ma finisce quasi sempre per scegliere gli stessi. In fondo c’è una giacca verde che non ricorda più di avere. Precisiamo subito che Marta è un personaggio narrativo, non il risultato di uno studio utenti. Il contesto ambientale, invece, è reale: secondo l’EEA, nel 2022 nell’Unione Europea si consumavano circa 19 chilogrammi di tessili per persona e se ne generavano circa 16 come rifiuto. Con ClosetAI non vogliamo colpevolizzare Marta e non vogliamo dirle automaticamente di comprare. Vogliamo restituirle memoria e contesto: cosa possiede, cosa usa, cosa sta trascurando e quale decisione può allungare la vita di un capo.""",
    """Qui cominciamo il percorso con una foto. Marta fotografa un capo e crea una scheda con immagine, categoria, colore, prezzo e data di acquisto, quando disponibili. Sottolineiamo un punto: la scheda non è una verità prodotta dall’AI. I dati restano visibili e Marta può correggerli. La foto diventa l’ingresso semplice a un record strutturato, che collegheremo agli utilizzi, allo stato e alle azioni successive. Separiamo anche due concetti che è facile confondere: descrivere il capo serve a organizzarlo; diagnosticare il suo stato di conservazione è un’analisi distinta, che vedremo fra poco. Dal lato utente vogliamo mantenere il gesto molto semplice: una foto, pochi controlli e il capo entra nel guardaroba digitale.""",
    """Passiamo ora all’uso quotidiano. Quando Marta indossa un capo, registra un utilizzo. Questo gesto costruisce nel tempo la cronologia reale del guardaroba e rende leggibile ciò che prima era soltanto una sensazione. Mostriamo quante volte il capo è stato usato e calcoliamo il cost-per-wear, cioè il prezzo diviso per il numero di utilizzi registrati. Precisiamo che non è una misura del valore affettivo e non vuole spingere a usare ossessivamente ogni oggetto: è un indicatore orientativo. Se gli utilizzi non sono stati registrati, il dato è incompleto. Con questa cautela, Marta può confrontare acquisto e uso effettivo, riconoscere i capi centrali e capire quali invece stanno occupando spazio senza entrare nella sua routine.""",
    """Ora apriamo la schermata Oggi. Qui proponiamo combinazioni usando regole comprensibili. Il punteggio pesa per il 55 per cento la compatibilità dei colori e per il 35 per cento il meteo; può aggiungere fino al 15 per cento per un capo fantasma eleggibile e applica un piccolo aggiustamento dal feedback, pari a più o meno 4 per cento. Così possiamo far riemergere la giacca di Marta senza imporla. Ci teniamo a dirlo chiaramente: questo recommender non è una rete neurale addestrata e, nel ranking attuale, non usa né Chroma né gli embedding Fashion-CLIP. L’occasione scelta viene salvata, ma oggi non modifica ancora il punteggio. La presentiamo quindi come sviluppo futuro, non come funzione già realizzata.""",
    """A questo punto rispondiamo direttamente alla domanda sui ghost garments: sì, li rileviamo. La regola è deterministica, non machine learning. Consideriamo fantasma un capo ancora attivo, senza alcun utilizzo registrato e posseduto da almeno la soglia scelta, 30 giorni per default. Usiamo la data di acquisto e, se manca, la data di inserimento. Quindi intendiamo “mai indossato dopo almeno 30 giorni”, non semplicemente “usato poco”: un capo indossato una volta non è ghost secondo questa definizione. Nell’interfaccia lo mostriamo come metrica “Capi fantasma” e lista “Capi da riscoprire” nella dashboard, come badge “Fantasma · mai indossato da 30+ giorni” nel dettaglio e come segnale “Anti-fantasma” nella proposta di oggi.""",
    """Ritrovata la giacca, ci chiediamo in che stato sia. Distinguiamo tre classi: buono, usurato e danneggiato, e colleghiamo l’esito a una decisione di cura. Se abbiamo foto e checkpoint, usiamo Fashion-CLIP pre-addestrato come estrattore visivo e la nostra piccola rete MLP per classificare. Se il modello o l’immagine non sono disponibili, passiamo a un’euristica basata su età e numero di utilizzi; nel risultato indichiamo anche quale sorgente è stata usata. Marta può poi correggere manualmente lo stato. Non lo presentiamo come una certificazione professionale: il modello riduce l’incertezza visiva, il fallback mantiene il flusso utilizzabile e la persona conserva l’ultima parola.""",
    """Ora allarghiamo lo sguardo dal singolo capo all’intero guardaroba. Con la gap analysis non chiediamo semplicemente “cosa manca da comprare?”, ma “il guardaroba copre davvero le esigenze principali?”. Consideriamo quantità per categoria, stagionalità, varietà cromatica, presenza di neutri e quota di capi fantasma. Possiamo suggerire un capospalla versatile, ma possiamo anche concludere che non serve acquistare nulla o avvertire che ci sono già troppe magliette. La rete produce sei etichette possibili e noi le traduciamo in un consiglio leggibile, preferendo riuso e seconda mano. Se il checkpoint non è disponibile o la predizione fallisce, ricadiamo sulle regole esperte usate come riferimento. Anche qui il modello aggiunge probabilità, ma la decisione rimane spiegabile e verificabile.""",
    """Torniamo infine alla giacca di Marta e chiudiamo il ciclo con un’azione: continuare a usarla, ripararla, donarla, venderla oppure avviarla alla corretta seconda vita. L’impatto verde che mostriamo è una stima di scenario, non una misura fisica e non una Life Cycle Assessment completa. Il calcolo è trasparente: media indicativa della categoria moltiplicata per il fattore associato all’azione, con risultato in chilogrammi di CO₂ equivalente stimata. Ci serve per confrontare ordini di grandezza e rendere visibile l’effetto potenziale di una scelta. Dipende però dall’ipotesi che quella scelta eviti davvero, almeno in parte, un nuovo acquisto. Per correttezza parliamo sempre di “stima” e di “scenario”; come sviluppo proponiamo dati per materiale, intervalli d’incertezza e fonti LCA più granulari.""",
    """A questo punto possiamo rileggere tutta la storia: Marta fotografa, registra gli utilizzi, riscopre la giacca, ne valuta lo stato, controlla se esiste un vero gap e sceglie come prendersene cura. Nel database dimostrativo locale abbiamo 12 capi, 148 utilizzi registrati, 2 capi fantasma e 57,5 chilogrammi di CO₂ equivalente stimata da 2 azioni circolari. Precisiamo che questi numeri rendono la demo coerente e ripetibile: non sono risultati di un test con utenti e non dimostrano un impatto ambientale reale. Fin qui abbiamo mostrato che ogni numero corrisponde a una decisione visibile nell’interfaccia. Ora cambiamo prospettiva e rispondiamo alla domanda tecnica: quale tipo di intelligenza produce ciascun risultato?""",
    """Per non chiamare tutto “AI”, separiamo quattro categorie. Primo: Fashion-CLIP è un modello visivo pre-addestrato da altri; noi lo usiamo congelato, senza riaddestrarlo. Secondo: le due teste MLP per stato e gap sono modelli che abbiamo addestrato noi e di cui salviamo i checkpoint. Terzo: ghost garments, cost-per-wear, ranking outfit e stima dell’impatto sono formule, regole o tabelle esplicite. Quarto: descrizioni, coach testuale e virtual try-on possono usare modelli generativi esterni, ma sono opzionali. Se ci chiedete di approfondire una funzione, possiamo quindi dichiarare con precisione input, trasformazione, output, metrica e limite. La nostra scelta progettuale non è massimizzare il numero di modelli, ma usare il livello di complessità giusto per ogni problema.""",
    """Entriamo ora nei due modelli che abbiamo addestrato e che entrano nel prodotto. Per lo stato, Fashion-CLIP rimane congelato e produce un embedding di 512 valori; una nostra MLP lo trasforma nelle classi buono, usurato e danneggiato. Sul holdout locale di un dataset di circa 600 immagini otteniamo circa il 94 per cento di accuracy, ma non abbiamo ancora una validazione esterna: è una prova di prototipo, non una garanzia su qualsiasi foto. Per i gap, una seconda MLP riceve 14 segnali aggregati e produce 6 etichette; su 5.000 guardaroba simulati raggiungiamo una micro-F1 di circa 0,945. Le label derivano da regole, quindi servono dati reali. Abbiamo preparato cinque notebook autonomi e commentati: due riproducono i modelli runtime; tre documentano esperimenti accademici su rischio ghost, previsione degli utilizzi e clustering, che non sono collegati alla UI.""",
    """Ora possiamo chiarire perché una parte importante dell’app funziona anche senza AI generativa. La regola ghost è un controllo logico; il cost-per-wear è una divisione; outfit e impatto sono punteggi e fattori dichiarati. Li abbiamo mantenuti espliciti perché qui il criterio deve essere stabile e spiegabile. La generazione entra invece come livello opzionale: un LLM può rendere più naturale una descrizione o il coach, mentre un modello diffusion può creare una prova visuale di virtual try-on. Sono modelli esterni e non addestrati da noi. Inoltre il try-on è una simulazione estetica: non verifica taglia, vestibilità o comportamento reale del tessuto. Se i servizi generativi non sono configurati, il nucleo del prodotto continua a funzionare con testi e logiche locali. Per noi questo è un punto di robustezza, oltre che di trasparenza.""",
    """Dal punto di vista architetturale, il client React responsive parla con API FastAPI; i servizi gestiscono guardaroba, utilizzi, ghost, raccomandazioni, gap e circolarità; SQLite, immagini e checkpoint costituiscono lo strato dati del prototipo. Questa separazione permette di creare una versione smartphone senza riscrivere il backend. Il passo più rapido è una PWA con manifest, service worker e supporto offline; Capacitor può portare la stessa interfaccia negli store, mentre React Native avrebbe senso solo per un’esperienza nativa più profonda. Prima della produzione servono autenticazione, isolamento tra utenti, HTTPS, storage sicuro, politiche sulle immagini e verifica GDPR. Chiudo quindi con la scelta guida del progetto: usare l’AI dove riduce davvero l’incertezza e mantenere spiegabile tutto il resto. ClosetAI vuole aiutare a comprare meno usando meglio ciò che c’è già.""",
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    deck = Presentation(args.input)
    if len(deck.slides) != len(NOTES):
        raise ValueError(f"Expected {len(NOTES)} slides, found {len(deck.slides)}")

    for slide, note in zip(deck.slides, NOTES, strict=True):
        frame = slide.notes_slide.notes_text_frame
        frame.clear()
        frame.text = note

    deck.core_properties.title = "ClosetAI — Storia utente e scelte tecniche"
    deck.core_properties.subject = "Presentazione ufficiale su uso, cura, impatto e AI del guardaroba"
    deck.core_properties.comments = "Include 14 note orali in italiano, una per ogni slide."
    args.output.parent.mkdir(parents=True, exist_ok=True)
    deck.save(args.output)
    print(f"Saved {args.output} with {len(NOTES)} speaker notes")


if __name__ == "__main__":
    main()
